apiVersion: apps/v1
kind: Deployment
metadata:
  name: dress-shop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dress-shop
  template:
    metadata:
      labels:
        app: dress-shop
    spec:
      containers:
      - name: dress-shop-container
        image: poodockerhub2025/dress-shop-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
